name: Greetings

on: [issues, pull_request_target]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: '  Hello there!👋 Welcome to the project!🚀⚡
  Thank you and congrats🎉 for opening your very first issue in this project.
  Please adhere to our [Code of Conduct](https://github.com/curiomind-e-learning/curiomind/blob/main/CONTRIBUTING.md).
  Please make sure not to start working on the issue, unless you get assigned to it.😄'
          pr-message: 'Congratulations!! for making your first PR at Curiomind, our mentors will review it soon. 🙌🏻'